### ISSUE TITLE
Enabling "Sorted by Time" or "Sorted by Timestamp" sorts logs in wrong order

### ISSUE THREAD

**Issue by ChronoTempus** [GENIVI/dlt-viewer#124]
![image](https://user-images.githubusercontent.com/58554773/98210624-82a72d80-1f49-11eb-892c-7c0b70fc6513.png)
I have this issue that whenever I apply a filter and for any group of rows there is same Time then rows will be sorted in descending order (in image can be seen that Index and Count are also in descending order).
Even if I try to sort by timestamp (which is not always possible if I have multiple life cycles in same dlt) if time is same rows will be in descending order
![image](https://user-images.githubusercontent.com/58554773/98211418-b0d93d00-1f4a-11eb-8a83-ee18c6223153.png)

I tried to find some settings that control this or something in source code itself, but didn't manage to fix this.

**Comment by OXINARF** [comment]
I was coming to report something very similar, but I don't have the issue when applying only filters, but only when "Sort by time" or "Sort by timestamp" is also enabled. @ChronoTempus can you confirm if that's your case too?

The problem that triggers my issue is with how Qt manages the QMultiMap entries with the same key: when you insert an entry, if there is an existing one with the same key, the new one will **precede** the existing one. Since the log is iterated on increasing index order, the later messages with the same time/timestamp will end up being first on the log.

@alexmucde I would suggest that the DltFileIndexerKey also got the index so that if time/timestamp is exactly the same, then they are ordered by the index. I can do a PR for that, if you want.

**Comment by ChronoTempus** [comment]
Can confirm if both checkboxes are disabled log is sorted correctly.

**Comment by OXINARF** [comment]
Ok, so it's the same issue. @ChronoTempus maybe change the title to something like "Sorting by time/timestamp is in the wrong order"?

**Comment by alexmucde** [comment]
Do you have any idea how to solve this issue? It would be even better if you can provide a pull request?

**Comment by alexmucde** [comment]
PR integrated.
